[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dstapi"
authors = [{name = "Jonas Wolff", email = "Jonas.wolff99@gmail.com"}]
dynamic = ["version", "description"]
